package lsp4custom.com.ninjacoder.customhtmllsp;

import io.github.rosemoe.sora.data.CompletionItem;
import io.github.rosemoe.sora.widget.TextSummry.HTMLConstants;

import java.util.List;

public class HtmlAttr {

    String[] ATTRIBUTES = {
            "accept",
            "accept-charset",
            "accesskey",
            "action",
            "align",
            "alt",
            "async",
            "autocomplete",
            "autofocus",
            "autoplay",
            "border",
            "bgcolor",
            "charset",
            "checked",
            "cite",
            "class",
            "color",
            "cols",
            "colspan",
            "content",
            "contenteditable",
            "controls",
            "coords",
            "data",
            "data-*",
            "datetime",
            "default",
            "defer",
            "dir",
            "dirname",
            "disabled",
            "draggable",
            "dropzone",
            "enctype",
            "face",
            "for",
            "form",
            "formaction",
            "headers",
            "height",
            "hidden",
            "high",
            "href",
            "hreflang",
            "http-equiv",
            "id",
            "ismap",
            "kind",
            "label",
            "lang",
            "list",
            "loop",
            "low",
            "max",
            "maxlength",
            "media",
            "method",
            "min",
            "multiple",
            "muted",
            "name",
            "novalidate",
            "onabort",
            "onafterprint",
            "onbeforeprint",
            "onbeforeunload",
            "onblur",
            "oncanplay",
            "oncanplaythrough",
            "oncanplaythrough",
            "onchange",
            "onclick",
            "oncontextmenu",
            "oncopy",
            "oncuechange",
            "oncut",
            "ondblclick",
            "ondrag",
            "ondragend",
            "ondragenter",
            "ondragleave",
            "ondragover",
            "ondragstart",
            "ondrop",
            "ondurationchange",
            "onemptied",
            "onended",
            "onerror",
            "onfocus",
            "onhashchange",
            "oninput",
            "oninvalid",
            "onkeydown",
            "onkeypress",
            "onkeyup",
            "onload",
            "onloadeddata",
            "onloadedmetadata",
            "onloadstart",
            "onmousedown",
            "onmousemove",
            "onmouseout",
            "onmouseover",
            "onmouseup",
            "onmousewheel",
            "onoffline",
            "ononline",
            "onpagehide",
            "onpageshow",
            "onpaste",
            "onpaste",
            "onpause",
            "onplay",
            "onplaying",
            "onpopstate",
            "onprogress",
            "onratechange",
            "onreset",
            "onresize",
            "onscroll",
            "onsearch",
            "onseeked",
            "onseeking",
            "onselect",
            "onstalled",
            "onstorage",
            "onsubmit",
            "onsuspend",
            "ontimeupdate",
            "ontoggle",
            "onunload",
            "onvolumechange",
            "onwaiting",
            "onwheel",
            "open",
            "optimum",
            "pattern",
            "placeholder",
            "poster",
            "preload",
            "readonly",
            "rel",
            "required",
            "reversed",
            "rows",
            "rows",
            "rowspan",
            "sandbox",
            "scope",
            "selected",
            "shape",
            "size",
            "sizes",
            "span",
            "spellcheck",
            "src",
            "srcdoc",
            "srclang",
            "srcset",
            "start",
            "step",
            "style",
            "tabindex",
            "target",
            "title",
            "translate",
            "type",
            "usemap",
            "value",
            "width",
            "wrap"
    };

    public HtmlAttr() {
    }

    public void install(List<CompletionItem> item, String prfex) {
        for (var items : ATTRIBUTES) {
            if (items.startsWith(prfex)) {
                item.add(attr(items, "Attribute"));
            }
        }
    }

    private CompletionItem attr(String attr, String desc) {
        final var item = new CompletionItem(attr, attr.concat("=\"\""), desc);
        item.cursorOffset(item.commit.length() - 1);
        return item;
    }
}
